def reset(lbl1, lbl2, lbl3, lbl4, lbl5, lbl6, lbl7, lbl8, lbl9, lbl10, lbl11, lbl12, lbl13, lbl14, lbl15):
    lbl1["text"] = ""
    lbl2["text"] = ""
    lbl3["text"] = ""
    lbl4["text"] = ""
    lbl5["text"] = ""
    lbl6["text"] = ""
    lbl7["text"] = ""
    lbl8["text"] = ""
    lbl9["text"] = ""
    lbl10["text"] = ""
    lbl11["text"] = ""
    lbl12["text"] = ""
    lbl13["text"] = ""
    lbl14["text"] = ""
    lbl15["text"] = ""